name: Teams
main: dev._2lstudios.teams.Teams
version: 0.0.1
author: 2LS
soft-depend:
  - "WorldSentinel"
depend:
  - "PlaceholderAPI"
  - "Vault"
commands:
  teams:
    description: Main command of the Teams plugin.
    usage: /teams
    aliases: [f, g]
  tl:
    description: Tells your location to members of your team
  hq:
    description: Takes you to your faction headquarters